[options]


addons_path = /opt/odoo/odoo19/addons,/opt/odoo/custom/onedesk
db_host = False
db_port = 5432
db_user = odoo_db
db_password = Mervo9898lma5p
admin_passwd = Mervo9898lma5p
logfile = /var/log/odoo/odoo.log
default_productivity_apps = True
onedesk_encryption_key = D9PNkpmqfZNSCVP5A9a5-s2bAbdvjE2ql3vGxaj6Tgg=
smtp_server = localhost
smtp_port = 1025
smtp_ssl = False
smtp_user =
smtp_password =
