[options]

# --- ADDONS ---
addons_path = /opt/odoo/odoo/addons,/opt/odoo/addons

# --- DATABASE ---
db_host = 127.0.0.1
db_port = 5432
db_user = odoo
db_password = MervoProd123!
db_name = odoo_prod
dbfilter = ^(odoo_prod|onedesk_client_.*)$
proxy_mode = True
list_db = False

# --- ADMIN ---
admin_passwd = Mervo9898lma5p

# --- LOGGING ---
logfile = /var/log/odoo/odoo.log
log_level = info

# --- PERFORMANCE ---
workers = 4
max_cron_threads = 2
limit_memory_soft = 2147483648
limit_memory_hard = 2684354560
limit_time_cpu = 60
limit_time_real = 120

# --- ONEDESK CUSTOM ---
onedesk_encryption_key = D9PNkpmqfZNSCVP5A9a5-s2bAbdvjE2ql3vGxaj6Tgg=
onedesk_filestore_path = /home/odoo/.local/share/Odoo/filestore



