[options]

addons_path = /opt/odoo/odoo-test/addons,/opt/odoo/odoo-prod/addons

; --- DATABASE ---
db_host = 127.0.0.1
db_port = 5432
db_user = odoo_prod
db_password =MervoProd123!
db_name = odoo_prod

; --- ADMIN ---
admin_passwd = Mervo9898lma5p

; --- LOG ---
logfile = /var/log/odoo/odoo.log

default_productivity_apps = True

; --- ONEDESK CUSTOM ---
onedesk_encryption_key = D9PNkpmqfZNSCVP5A9a5-s2bAbdvjE2ql3vGxaj6Tgg=

; --- SMTP (DEV) ---
smtp_server = localhost
smtp_port = 1025
smtp_ssl = False
smtp_user =
smtp_password =